---
title: "Accounting for Global COVID-19 Diffusion Patterns, January-April 2020"
authors: Yothin Jinjarak, Rashad Ahmed, Sameer Nair-Desai, Weining Xin, Joshua Aizenman
output: html_document
---

Abstract
This paper takes stock of the daily data gathered until April 28, 2020, tracing the associations between COVID-19 mortality and policy interventions that aim to limit social contact and containment, accounting for global pandemic diffusion patterns.  A panel local projection analysis suggests that, with a lag, more stringent pandemic policies were associated with significantly lower mortality growth rates.  The association between stringent strict pandemic policies and lower future mortality growth is more pronounced in countries with a greater proportion of the elderly population, higher density, greater proportion of employees in vulnerable occupations, greater democratic freedom, more international travels, and further distance from the equator. Countries with greater policy stringency in place prior to the first death also realized lower peak mortality rates and flatter mortality curves. Countries with greater elderly population share or with higher degrees of initial mobility had higher peak mortality rates in the first phase of the pandemic. A survival analysis of the number of days until new mortalities peak suggests that countries adopting more stringent policies early on had significantly lower durations to the first mortality peak, while mortality rates took longer to peak in countries that are considered more democratically free, and those further from the equator.  More data and research are needed to achieve sharper identification of these factors.


JEL No. F 5, I 18
 

	Introduction and Overview                
This paper takes stock of the data gathered during the first three months of the COVID-19 pandemic, tracing the associations between COVID-19 mortality and pandemic policy interventions, accounting for global pandemic diffusion patterns. Pandemic policy interventions in our consideration refers to containment and closure policies that aim to limit social contact. Anecdotal evidence and policy dynamics suggest that accelerated COVID-19 mortality induces a tighter pandemic policy response aimed at slowing the otherwise geometric patterns of the pandemic.  With a lag of several weeks, these policies opt to reduce the mortality rate, at a strength that may vary systematically across countries. Specifically, as COVID-19 mortality affects disproportionally the older population and people with pre-existing conditions, a given increase in policy intensity may have a greater proportionate impact on future mortality in older societies, and in countries with a greater average exposure to pre-existing medical conditions.  In the same vein, higher urbanization rates, higher population density and mobility, other things being equal, opt to magnify the decline in future mortality rates associated with a more aggressive pandemic policy stance.   
Key factors in modeling a pandemic and in guiding policy-making include the infection rates; the mortality rates associated with infections; the ability and effectiveness of the policies, medical system, and society to adapt to the changing dynamics of a pandemic; and other structural factors [Verity, Okell, Dorigatti et al. (2020)].  Our empirical specification controls for these considerations, subject to the limited data available on key factors.  Specifically, the scarcity of COVID-19 testing, and the limited information on the precision of available tests, implies a vast underestimation of the infection rates per capita, possibly by a factor of two digits.  The undercount of COVID-19 population mortality rates is also prevalent, but by an order of magnitude below the errors associated with infection rates.   Thereby, we focus mostly on accounting for the COVID-19 population mortality rates per capita during the first phase of the pandemic, controlling for policy and structural factors subject to data availability and quality.  We plan to revisit these issues with better quality and longer-term data in the coming quarters. 
 A fair share of the countries reached a local peak of COVID-19 population daily new mortality rate curve during the sample period [see Figures 1 and 2].  Applying various techniques, we study the factors accounting for the empirical shape of the mortality curve from the onset of the pandemic to the local peak, with a focus on the impact of policy intensity interacting with structural variables.  Like most similar studies, one should use healthy skepticism in reading the results.  First, data quality and availability are a major limitation, as each country has its challenges with data collection, aggregation, and reporting.  Second, ‘better performance’ in the first mitigation phase of a pandemic does not guarantee superior future performance, as the dynamics of a new viral pandemic are yet unknown.  By design, flattening the pandemic curve shifts some mortality incidence forward. The susceptibility to secondary waves of infection remains a looming threat. Policies adopted in the second quarter of 2020, and the realized pandemic infections, containment, and treatment will explain the future performance of each country.  Furthermore, only time and much more medical research will tell the degree to which infected persons that recovered gained immunity for a long enough period to allow smooth convergence to ‘herd immunity.’
Our study relies on daily COVID-19 policy and case data reported by Oxford and John Hopkins University, as well as Apple mobility data and various controls. Our baseline estimation study examines OECD and Emerging Market (EM) sub-samples based on data from 1/23/2020 – 4/28/2020; or the first 97 days of the pandemic. Below, we summarize the main results.
First, we investigate the evolution of weekly mortality growth rates over time and across countries. Applying dynamic panel analysis, local projections (Jorda, 2005) suggest that administering more stringent pandemic policies were associated with significantly lower mortality growth rates during the first pandemic phase (i.e., during the time to the first local peak of mortality/day curve).  Countries with a Stringency Index (SI) 10 units higher than average had, two weeks later, mortality growth rates that were on average -3% lower (Oxford’s SI is normalized between 0 to 100; where 100 = strictest response). The reduction in mortality growth grows to roughly -6% by the third week and then stabilizes. While the reduction in growth rates seems quite large, it is important to put these numbers in perspective. Given the exponential nature of disease spread, often times weekly mortality growth rates can be anywhere from +50% to +100% or greater.   
Taking slow-moving country fundamentals from the period pre-COVID-19 as exogeneous, we find that countries in the 75th percentile in terms of proportion elderly (65 or older) saw a much stronger reduction in mortality growth rates from the same 10 unit rise in SI, compared to countries with relatively low proportions of elderly (25th percentile). Countries in the 75th (25th) percentile saw mortality growth rates about -9% (-3.5%) after two weeks. Countries with a greater proportion of elderly are unconditionally more susceptible to the pandemic, but for this same reason, are likely to benefit more under stringent policies. In countries further away from the equator, SI measures had a stronger impact on mortality growth than countries closer to the equator. This heterogeneity may be consistent with what some describe as a temperature risk factor associated with many flu viruses. Countries with cooler temperatures over the Jan-April period, and countries with higher proportions of elderly, may be at higher risk with regards to COVID-19, and therefore the effectiveness of stringency measures for these countries is stronger. Greater policy stringency is also more strongly associated with lower mortality growth during the first phase of the pandemic in countries with greater population density, greater proportion of employees in vulnerable occupations, and greater democratic freedom (measured with the EIU Democracy Index), but the economic significance is not as stark as for countries with more elderly populations, or those farther from the equator. While population density and employees in vulnerable occupations are quite intuitive risk factors for a pandemic like COVID-19, the role of democratic freedom is an ongoing topic of debate. Our results are consistent with the view that greater individual rights may be detrimental in this situation, making it more difficult for the government to place strict quarantines in place and have citizens abide by them.
Next, we turn to cross-country regression results, where the dependent variables include the logged peak mortality rate (calculated as the cumulative deaths out of the population at the peak of daily new mortality, by country), the logged peak new mortality rate (calculated as the new deaths out of the population at the peak of daily new mortality, by country), and the ratio of ‘peak new mortality rate’-to-‘pandemic duration to first peak’ measured in days (a proxy flatness/steepness of the mortality rate curve). Countries with higher early mortality (cumulative mortality within the first week following the first death) tend to have higher new mortality peaks but flatter mortality curves in the first pandemic phase. In addition, countries with more aggressive policy interventions in place prior to the first death tend to exhibit lower cumulative and new mortality at the peak, and flatter mortality curves. We find that one unit increase in Early SI is associated peak cumulative and new mortality rates of -3% and -2.5% lower, on average. Countries with greater elderly populations tend to have had higher peak mortality rates. We also find some evidence suggesting that countries with higher mortality growth rates at the outbreak also had higher peak mortality rates.  Overall, the evidence suggests (but does not necessarily assert) that policy stringency directly reduced the peak mortality rates and flattened the mortality curve, and that other forces were also at play (e.g. demographics, initial pandemic conditions). 
Not only do mortality rates during the first pandemic phase differ across countries, but there is also considerable variation in how long new deaths continued to climb in terms of days. We term this as the ‘pandemic duration to the first peak’ (PD). One should be careful when interpreting the effects of covariates on the PD in terms of altering the shapes of mortality curves, as a longer PD could be accompanied by a higher peak mortality rate and thus a steeper curve or a lower peak mortality rate and thus a flatter curve. Fitting a Kaplan-Meier curve for the PD over all countries in the sample, in number of days,  suggests that countries with stronger Early SI measures (SI > 19) had significantly lower PDs on the way to the first local peak of the mortality/day curve, compared to countries which did not (SI < 19). Of countries with an Early SI of less than 19, it took on average 50 days for the probability of peaking to reach 75%. In contrast, countries with Early SI greater than 19 reached the same probability within around 40 days. To better understand the cross-country variation in PD, under a Cox proportional hazards model, we report that across most (but not all) specifications, stricter initial policy interventions are associated with shorter durations of the PD. Higher mortality rates early on are associated with shorter pandemic durations to the peak, while countries realizing higher mortality peaks tend to have, unsurprisingly, longer pandemic durations to the peak. Additionally, countries with greater elderly populations, higher population density, greater shares of vulnerable employment tend to exhibit shorter pandemic durations to the peak.  Moreover, under certain specifications, the level of democratic freedom appears to be a highly significant determinant in pandemic duration to the peak. That is, countries that are considered more ‘democratically free’ saw longer pandemic durations to the peak. Countries further away from the equator also tended to experience longer PD. While at this stage we are reporting suggestive statistical associations, more data and research are needed to get fuller identifications of all these factors.

	Empirical Specification
We study three characteristics of COVID-19 mortality over the first three months of the pandemic: first, the weekly growth rate of the cumulative mortality rate per capita; second, the peak cumulative mortality rate per capita; and third, the time-to-peak of new mortality rate per capita, which we refer to as ‘pandemic duration to the first peak’ (PD). Our data on mortality rates of COVID-19 spans the period from January 23rd, 2020 to April 28th, 2020. To filter out noise in the daily mortality data, we construct a 7-day rolling average of the daily and cumulative mortality rate per capita and use these series of averages in our estimations. For simplicity, the mortality rate mentioned hereafter is referred to as the 7-day rolling average of the mortality rate.  
II.i. Policy stringency and mortality dynamics
We start with a panel study of mortality growth rate dynamics, using the week-over-week growth rate of the cumulative mortality rate per capita, accounting for containment and closure policy interventions (see Oxford’s COVID-19 Government Response Tracker).  Specifically, our dependent variable y_(i,t) in country i on date t is defined as
(1)
y_(i,t)=〖log(MortalityRate〗_(i,t))-〖loga(MortalityRate〗_(i,t-7)),
where MortalityRate_(i,t) is the cumulative mortality rate of country i at time t. A lower growth rate of the cumulative mortality rate implies a flattening of the cumulative mortality curve. 
Our first benchmark estimation uses the method of local projections (Jorda, 2005), examining future (or current) mortality growth rate as a function of current (or past) mortality growth rate and degree of policy stringency. We aim to understand to what degree policy interventions are associated with future mortality growth, and therefore, the evolution of the pandemic. Local projections do not only simplify our problem but also produce robust estimates under misspecification. Specifically, our model is 
(2)
y_(i,t)=α_i+δt+βy_(i,t-τ)+γz_(i,t-τ-7)+ϵ_(i,t),
where y_(i,t) is the week-on-week growth rate of the cumulative mortality rate in country i on date t, y_(i,t-τ) is the lagged mortality growth rate, and z_(i,t-τ-7) is the lagged stringency index constructed in the Oxford COVID-19 Government Response Tracker, an aggregate measure of the overall stringency of containment and closure policies. Fixed effects are denoted as a_i and δt, representing country and time fixed effects, respectively. The subscript τ denotes the preceding first, second, third, or fourth week, which allows us to explore whether the association between policy interventions and mortality growth is persistent or not, if it exists. Additionally, we study the heterogeneity in the effect of policy interventions on mortality growth rate by estimating the model with interaction terms between lagged stringency index and country-specific social and economic variables
(3)
y_(i,t)=α_i+δt+βy_(i,t-τ)+γz_(i,t-τ-7)*x_i+ϵ_(i,t),
where x_i is the country-specific variable of interest. We consider proportion of the elderly population (people aged 65 and over), proportion of urban population, proportion of employment in vulnerable sectors, population density, GNI per capita, health expenditure (% of GDP), population-weighted exposure to ambient PM2.5 pollution, logarithm of tourist arrivals and departures, latitude and longitude, and quality of democracy. 
II.ii Cross-country differences in peak mortality
We follow with a cross-country analysis examining mortality per capita at the peak, a key moment in the first quasi-bell curve which puts hospitals’ capacity to its most severe test. The quasi-bell shapes are normalized by the day of first significant death. We consider three variables related to the peak: first, the logged cumulative mortality rate at the peak of daily mortality rate, second, the logged peak daily mortality rate, and third, the ratio of the logged peak daily mortality rate to the PD. A higher cumulative mortality rate at the peak implies a greater cumulative need for hospitalization, and a higher daily mortality rate at the peak implies a larger inflow of patients, both stressing hospitals’ capacity. Accounting for the pandemic duration to the first peak, a higher ratio of the peak daily mortality rate to the PD implies a larger and/or faster patient inflow that could potentially overwhelm the healthcare system.
Our cross-country peak mortality data is calculated from the sample from January 23rd, 2020 to April 28th, 2020, during which many OECD countries and emerging market economies finished their ride up to the first peak of the first quasi-bell in terms of contagion per capita and fatality per capita. Our cross-sectional model is
(4) 
y_i=β_0+Z_i γ+X_i β+ϵ_i,
where y_i is one of the three mentioned outcome variables related to the peak mortality rate in country i. We include a set of potential endogenous variables Z_i. First, one may be interested in whether the cross-country difference in the intensity of the Covid-19 outbreak explains the cross-country evolution of the pandemic. We include loga〖(Early Mortality_i)〗, the logged cumulative mortality rate in the first week since the first death, and Early Mortality Growth_i, the growth rate of daily mortality rate in the first week since the first death, to control for the cross-country difference in the initial level and growth of mortality rate. Second, one may be also interested in whether early policy interventions influence the cross-country evolution of the pandemic. To account for these cross-country differences in the early level of policy stringency, we include Early Stringency_i, the weekly average of the stringency index one week prior to the first death. Additionally, to account for cross-country differences in how aggressively countries respond to the pandemic and increase their policy intensities, we include a covariate which we refer to as the SI Delta_i, calculated as the difference between a country’s maximum stringency index (SI) level and its average SI level in the week prior to the first death, normalized by the number of days (T) between them:
(5)
SI Delta_i=[maxa(SI_i )-SI_(i,-7) ]/T_i .
A higher maximum SI and/or a shorter time to the maximum SI will yield a higher SI Delta. Third, we include Early Mobility_i, the weekly average mobility index in terms of walking (reported by Apple) in the week prior to the first death. We emphasize that while these variables are important to investigate, all of them are endogenous, as they are calculated over part of the first wave period of COVID-19. We also include a set of country-specific control variables X_i that we take as exogenous, including proportion of the elderly population (people aged 65 and over), proportion of urban population, proportion of employment in vulnerable sectors, population density, GNI per capita, health expenditure (% of GDP), quality of democracy, and latitude and longitude.
II.iii. Cross-country differences in time-to-peak
We then proceed with a survival analysis studying the association between the pandemic duration to the first peak (PD) rate and a set of explanatory variables. The object of primary interest in our survival analysis is the survival function 
(6)             
S(t) = Pr(T>t),
which is defined as the probability that the pandemic duration to the first peak is later than date t. A higher probability that the PD is later than a certain date implies a longer PD, which could have ambiguous implications. On one hand, it suggests a slower surge in hospitalization that could ease the burden on the healthcare system. On the other hand, a longer time-to-peak may imply a longer-lived, poorly managed pandemic.  Our benchmark specification is the Cox proportional hazards model (Cox, 1972), which examines the relationship between the hazard function and a set of explanatory variables.  The hazard function is defined as the probability that the peak is on date t conditional on that the peak is reached until date t or later,
(7)
λ(t)=lim┬(dt→0)a〖(Pra(t≤T<t+dt))/(dt∙S(t))〗=-(S^' (t))/S(t) .
Our benchmark Cox proportional hazards model is
	(8)
λ(t│〖Z_i,X〗_i )=λ_0 (t)  expa(β_0+Z_i γ+X_i β),
where  λ(t│X_i ) is the hazard function for country i on date t, conditioning on a set of endogenous variables Z_i and exogenous variables X_i, and λ_0 (t) is the baseline hazard function. In addition to the same set of endogenous and exogenous variables as in the cross-country regression analysis, we also include the endogenous logged peak new mortality rate, to control for the cross-country difference in the peak level of mortality rates. The specification of the Cox Model implies that the effect on the hazard function of a one-unit increase in one covariate with coefficient δ is e^δ, and that the effect on the survival function is to raise it to a power given by the effect on the hazard function
(9)
S_1 (t)=〖S_0 (t)〗^(e^δ ),
where S_1 (t) is the survival function on date t for a group with a one-unit higher value of the covariate. A key underlying assumption of the Cox model is that hazard rates between groups are assumed to be proportional, or constant over time. We test whether this assumption is satisfied in our analysis.
II.iiii. Limitations
We wish to briefly call out the limitations of our research design. First, our estimates cannot (and should not) be interpreted as causal. What we are reporting, across all models, are associations. Some of our variables are endogenous, which may bias our estimates. Moreover, given our choice to investigate country factors one-by-one, our regression estimates may also be biased from omitting variables. To overcome these challenges, we are in the process of collecting additional data at varying levels of detail to help deal with these issues, with the aim of achieving cleaner identification going forward.

	Data
Our data links prudential and reactionary government interventions to COVID-19 mortality rates per capita, controlling for country-specific characteristics. We construct the mortality rates using the John Hopkins Center for Systems Science and Engineering (CSSE) COVID-19 data repository, which details confirmed cases and deaths across our sample period. This data, which is provided as a global panel at the provincial level, was aggregated to the country-level for the purposes of our estimation. The seven-day rolling average of the cumulative mortality rate per capita is calculated as the ratio of the cumulative total of country deaths by population, while the seven-day rolling average of the new mortality rate is the ratio of new daily deaths by population.  
The central covariates of interest were pulled from Oxford’s COVID-19 Government Response Tracker. As of April 29th, 2020, Oxford provides country-level indicators on containment and closure; economic responses; the quality of health systems; and unorthodox responses to the COVID-19 pandemic.  We focus our estimation on the stringency index (SI); which mainly captures variation in government policies related to containment and closure. Each nation is scaled with a composite score from 0-100, with higher scores indicating more stringent policy interventions. In our dynamic panel estimation, we lag these interventions by between 2-5 weeks, to account for delayed implementation or latent effects.
In addition to the Oxford data, we control for various country-specific features using a wide range of publicly available data. We pull country coordinates from Google, and integrate data on recent mobility trends from Apple.  From the World Bank, we gather World Development Indicators for the proportion of the population above age 65; the proportion of the population which is urban; total population density (people per 100 sq. km. of land area); tourist arrivals and departures; the proportion of vulnerable employment; gross national income per capita (calculated in current USD using the Atlas method); number of cellular subscriptions; current health expenditures; and micrograms of PM2.5 air pollution per capita.  We also include cross-country indicators of strength of democracy, from the Economist and Freedom House.  From the Correlates of War project; we aggregate data on military expenditures and personnel; iron and steel production; and energy consumption.  Lastly, we collect data on prior infections and deaths by disease through the World Health Organization’s International Classifications of Diseases.  This data is collapsed by country, across the years 2015-2018. Analysis is restricted to deaths by respiratory, endocrine, or high blood pressure conditions. We choose not to incorporate testing covariates, given discrepancies and measurement error in currently available data.  Depending on the quality of future data, we may choose to integrate these covariates in our future analyses.

	Estimation
We take a multi-faceted approach to understanding the cross-country dynamics of pandemic diffusion. As mentioned, the dynamic panel enables us to study to what degree stringency policies are associated with weekly cumulative mortality growth rates, and whether such policies start taking effect with a lag.  Instead of including several lags as in a traditional dynamic regression analysis, we estimate panel local projections (Jorda, 2005) with fixed effects to simplify the problem and preserve degrees of freedom. Moreover, local projection impulse responses are robust under model misspecification. We include mortality growth lagged by τ days and Stringency lagged by τ+7 days. We estimate the four specifications via LSDV  with mortality growth (the dependent variable) lagged from 1 week to 4 weeks, and SI lagged from 2 weeks to 5 weeks, respectively. Given that residuals within countries are likely correlated, we employ robust standard errors clustered on country. 
The cross-country analysis is simpler, focusing on accounting for the cross-country heterogeneity in mortality outcomes at the peak of the first quasi-bell curve. For this, we simply rely on OLS estimation, adjusting the standard errors for heteroscedasticity. Finally, we conduct a survival analysis to better understand what drives variation in pandemic duration to the first peak (PD) across countries. We estimate the Cox proportional hazard model via maximum (partial) likelihood. For robustness, we also test and report whether the proportional hazards assumption is satisfied.
IV.i. Stringency Policy and Mortality Dynamics
Table 1 reports the baseline results from the local projection regressions (dynamic panel analysis). Notice that across all local projection regressions, Stringency is statistically significant and negative. These cursory results suggest that countries administering more stringent pandemic policies realized, on average, significantly lower mortality growth rates, with a lag of 2 to 5 weeks (Figure 3). The size of the estimates are economically significant: countries with a Stringency Index (SI) 10 units higher than average had, two weeks later, mortality growth rates that were on average -3% lower. The reduction in mortality growth grows to roughly -6% by the third week and then stabilizes. While the reduction in growth rates seems quite large (and certainly should not be ignored), it is important to put these numbers in perspective. Given the exponential nature of disease spread, weekly mortality growth rates can be anywhere from +50% to +100% (or greater).
	In the baseline analysis (Table 1) we do not explore cross-country heterogeneity in mortality dynamics. However, it is of great interest to understand whether and to what degree stringency policies were more effective in some countries than others in slowing down mortality growth. In the Online Appendix, we report local projection results, allowing for the impact of SI to depend on each of our country fundamentals following Equation 3.  We take these country fundamentals as exogeneous, as they are from the period pre-COVID-19 and are slow-moving (e.g. population, democracy). Due to the number of country fundamentals we are interested in exploring, we estimate regressions one-by-one. While this greatly simplifies interpretation and preserves degrees of freedom, a key drawback of this approach is that it may suffer from omitted variables. 
Figure 4 summarizes the results into plots, highlighting the impact of a 10 unit rise in SI for countries in the 25th percentile of a given characteristic against those in the 75th percentile of the same characteristic. For example, notice that countries in the 75th percentile in terms of proportion elderly (65 or older) saw a much stronger reduction in mortality growth rates from the same 10 unit rise in SI, compared to countries with relatively low proportions of elderly (25th percentile): Countries in the 75th (25th) percentile saw mortality growth rates fall about -9% (-3.5%) after two weeks. These results are consistent with the proportion elderly being a risk factor for the pandemic. Countries with a greater proportion of elderly are unconditionally more susceptible to the pandemic, but for this same reason, stringency policies  may be more beneficial in these countries.
Another interesting characteristic is latitude, which describes the vertical positioning of the country. In countries on greater latitudes (further away from the equator) SI measures had a stronger impact on mortality growth than in countries closer to the equator. This heterogeneity may be consistent with what some describe as a temperature/seasonal risk factor associated with many flu viruses. Countries with cooler temperatures over the Jan-April period, like those countries with higher proportions of elderly, may be at higher risk with regards to COVID-19 severity, and therefore the effectiveness of stringency measures may be stronger. SI policies are also more strongly associated with lower mortality growth in countries with greater population density, greater proportion of employees in vulnerable occupations, and greater EIU Democracy, but the economic significance is not as stark as the it is for countries with more elderly populations or those further from the equator. While population density and employees in vulnerable occupations are quite intuitive risk factors for a pandemic like COVID-19, the role of democratic freedom is an ongoing topic of debate. Our results support the view that greater individual rights may be detrimental in the present situation, making it more difficult for the government to place strict quarantines in place and have citizens abide by them.
IV. ii. Cross-country differences in COVID-19 mortality
Cross-section regression results, where the dependent variable is the logged peak cumulative mortality rate (calculated as the cumulative deaths/population at the first peak of daily new deaths) are reported in Table 2, column [1]. In addition, we include results for outcome variables the logged peak new mortality rate (column [2]), and the ratio of the peak new mortality-to-PD (column [3]). Results vary from specification to specification, but a few broad patterns emerge. First, early stringency measures are significantly negatively associated across all specifications: Greater early stringency is associated with lower peak cumulative mortality rates (column [1], estimate of -0.029), peak new mortality rates (column [2], estimate of -0.025), and a flatter mortality curve (column [3], estimate of -0.005). The first two columns imply that countries with Early SI 1 unit higher than average realized cumulative and new peak mortalities that were about -3% and -2.5% lower. Table 2 [1] and [2] suggest that countries with higher levels of early mortality (mortality within the first week following the first death) don’t appear to have significantly higher cumulative or new mortality rates at the peak. However, column [3] shows that early mortality is significantly negatively associated with the ratio of peak new mortality-to-PD. Early mortality growth rates are positively and significantly associated with all three outcome variables (columns [1], [2], and [3]). It’s notable that the inclusion of early mortality growth in column [1] knocks out a statistically significant and positive estimate on elderly population. It’s possible that countries with higher early mortality growth rates are also countries with higher proportion elderly. These countries would realize more deaths early on given the at-risk population is larger. Population density, somewhat surprisingly, is negatively associated with all three outcome variables (column [1], [2], and [3]). However, this association may be driven by the fact that many of the high-density countries are in Asia. These very similar countries contained the spread of COVID-19 relatively effectively given their preparedness in light of battling SARS in 2003. We also find some evidence suggesting that countries with higher level of democratic freedom appear to have higher cumulative and new mortality rate at the peak, but not significantly different peak new mortality-to-PD.
As mentioned, one may also be interested in whether the rate of change in SI impacted the cross-country evolution of the pandemic. We do find negative, but insignificant associations with SI Delta across all outcome variables (columns [1], [2], and [3]). Taken together with the evidence from local projections in our panel analysis, these findings indicate (but do not assert) that 1) aggressive policy responses may have helped slow down the growth rate of mortalities with a lag, 2) having stringent policies in place early may have helped to lower peak cumulative and new mortality rates while also flattening the mortality rate curve. In contrast, the evidence on the effectiveness of changes in SI after the fact is much weaker.
IV.iii. Cross-country differences in pandemic duration to the first peak (PD)
Not only do mortality rates differ across countries, but there is also considerable variation in how long new deaths continue to climb, something we denote pandemic duration to the first peak (PD). Figure 5 visualizes basic characteristics on the PD, with 5a referring to mortality PD and 5b referring to confirmed case PD, respectively. The left-hand-side plots the Kaplan-Meier (KP) curve for the PD over all countries in the sample, in number of days. The y-axis reflects the probability that the 'peak is yet to come'. Therefore, higher (lower) values reflect lower (higher) odds that a country has reached peak daily deaths. We focus our attention on the mortality PD, as the underlying data is likely to be more accurate. It's clear that across countries, it took an average of 30 days for the probability of peaking to rise to 50%. By 40 days, the probability a country will peak is closer to 75% (i.e. the probability the peak is yet to come is 25%). The following two plots stratify countries based on their Early Stringency levels. The average Early SI was about 19. The center plot KP curve shows, that countries with stronger Early SI measures (SI>19) had significantly lower PD compared to countries which did not (SI<19). Of those countries with Early SI less than 19, it took on average almost 50 days for the probability of peaking to reach 75%. In contrast, countries with Early SI greater than 19 reached the same probability within about 40 days.
Table 3 reports results from the survival analysis, which tries to understand the cross-country variation in the pandemic duration to the peak (PD) (see also the Online Appendix for alternative specifications). In the Cox model, the dependent variable is the (survival) probability that a country is ‘yet-to-peak’ -- column [1] for mortalities and column [2] for confirmed cases. Hence, significant positive (negative) coefficients reflect covariates which are associated with earlier (later)-than-average peaking, in terms of days. Across most specifications in the Online Appendix, Early Stringency (the weekly average level of SI in the week prior to the first death) is significant and positive, suggesting that stricter initial stringency measures may influence the PD by shortening it, all other things being equal. The estimate is also significantly positive in the fully specified model for mortality (Table 3, column [1]), but insignificant for confirmed cases (Table 3, column [2]). We emphasize that this result does not indicate that stricter policies early on are associated with steeper mortality curves, as evidence in our cross-country analysis on the peak mortality rate shows that stricter policies early on are also significantly associated with lower peaks.
Higher mortality rates early on are associated with shorter PD, while higher peak mortality is associated, unsurprisingly, with longer PD. Additionally, countries with greater elderly populations, higher population density and greater shares of vulnerable employment tend to exhibit shorter PD. This result, which seems counterintuitive, is consistent with our findings in the dynamic panel analysis, where countries exhibiting these same risk factors also had stronger associations with stringency policies in terms of reducing future mortality growth. The level of democratic freedom appears to be a highly significant determinant of the PD (Online Appendix) but loses significance in the fully specified model (Table 3 column [1]). That is, countries that are considered ‘freer’ saw longer PD. Finally, there is a significant geographic factor, where countries further from the equator tend to experience greater PD. We also find that early mortality growth rates were not a significant determinant of the PD but exhibited significantly positive effects on shortening the PD (column [1] and [2]).
It is important to point out that not all of our survival specifications appear to pass the proportional hazards assumption of the Cox regression model. We report the test statistic of Grambsch and Therneau, (1994)] for all model specifications. Neither the Cox model using confirmed cases data nor that using the mortality data rejects the null of proportional hazards. 
IV.v. Discussion
To summarize, the role of country-specific factors in the diffusion of COVID-19 varies widely and depends on the outcome of interest – whether it is weekly mortality growth, peak mortality, or pandemic duration to the peak. From our dynamic panel local projections, we find that higher SI levels were significantly associated with lower weekly mortality growth with a 2-week lag, and the effects remain significant at least through 5 weeks. We estimate that on average, countries with SI indices 10-units higher than average saw mortality growth rates that were -3% lower two weeks later, and -6% lower three, four and five weeks later. This dynamic impact of higher SI levels is stronger in countries which appear to be more vulnerable to COVID-19 type breakouts: countries with greater elderly populations, cooler temperatures, and to a lesser degree, countries with higher population density, a larger share of vulnerable employment, and higher levels of democratic freedom. 
While we find evidence of a dynamic effect of policy stringency on weekly mortality growth, we also find significant cross-country evidence that more stringent policies early on (i.e., stringent policies in place one week prior to the first death) are associated with lower peak cumulative and new mortality rate levels along with a flatter mortality curve (lower ratios of peak new mortality rate-to-PD) over the January-April window (first wave). We do find some weaker and less conclusive evidence suggestive of stronger early policies being associated with shorter pandemic durations to the first peak (PD), while geography (being farther from the equator) and greater democratic freedom were associated with longer PD.	

	Related Studies
Avery et al. (2020) provides an overview on the modelling of the spread of COVID-19. By and large, the ongoing challenges surround data on the infection rates. As noted by Manski and Molinari (2020), because of missing data on tests for infection and imperfect accuracy of tests, reported rates of population infection by the SARS CoV-2 virus are lower than actual rates of infection, resulting in infection fatality rates that are lower than reported. In addition, as argued by Atkeson (2020), in the presence of effective mitigation measures, the model with a high initial number of active cases and a low fatality rate gives the same predictions for the evolution of the number of deaths in the early stages of the pandemic as the same model with a low initial number of active cases and a high fatality rate. To ameliorate these data issues, our study uses the mortality rate per capita as the main variable of interest.  In this section, we synthesize our estimates with findings from related studies in the field. Notwithstanding different empirical specifications across studies, we find our main results are consistent with the literature and offer valuable new evidence.
V. i. Mortality rates
Closely related to our study are The Economist (2020) and Stojkoski et al. (2020). The Economist’s study review uses a sample of U.S. states focusing on the case-fatality rate. It finds the following associations between the case-fatality rate and the listed variables, ordered by their significance (one standard deviation increase): median age (pos.), ICU beds per 100,000 people (neg.), population density (pos.), and median income (neg.), the prevalence of heart disease, diabetes and smoking (pos.), the share of the population that is African-American (pos.), and amount of social distancing three weeks prior (neg.). Stojkoski et al.’s study findss that a one percent increase in government intervention, measured by the stringency index as in our studyresearch, is associated with -0.93 percent change in the mortality per capita. Our findings are consistent with this. Given our most comprehensive specification in the cross-country estimates, we find a significant association between the stringency index and the mortality rate levels (Table 2, columns [1] and [2]). An increase of 1 unit of the stringency index is statistically associated with -3 percent decrease in the peak cumulative mortality rate (Table 2, column [1]), and a -2.5 percent decrease in the peak daily mortality rate (Table 2, column [2]). 
V. ii. Demographics and culture
Our study finds supportive evidence for the role of the aging population, urbanization, pre-existing conditions, mortality from high-blood pressure, obesity, diabetes, and trust. The findings are consistent with case studies on the association between social networks and COVID-19 infection. Kuchler, Russel, and Stroebel (2020) find in Facebook data that areas with stronger social ties to two early COVID-19 "hotspots" (Westchester County, NY, in the U.S. and Lodi province in Italy) generally have more confirmed COVID-19 cases, after controlling for geographic distance to the hotspots as well as for the income and population density of the regions. Allcott et al. (2020) find in location data from a large sample of smartphones to show that areas with more Republicans engage in less social distancing (controlling for other factors including state policies, population density, and local COVID cases and deaths, pointing to significant gaps between Republicans and Democrats in beliefs about personal risk and the future path of the pandemic. Fetzer et al. (2020) find that the perception of a weak government and public response is associated with higher levels of worries and depression, and that strong government reactions correct misperceptions, and reduce worries and depression. Our findings on the association between trust, the stringency index, and mortality from COVID-19 yield consistent messages along this line.
V.iii. Geography
We find that the mortality growth rates are associated with the impact of stringency policies interacted with distance from the equator: countries in higher latitude appear to benefit more from stringency policies, as they are associated with lower mortality growth from a 10-unit rise in stringency relative to countries which lie closer to the equator. This evidence suggests that geographic location may be a potential COVID-related risk factor such that stringency measures are more effective in higher risk, high latitude countries. The finding is consistent with evidence linking temperatures to the spread of influenza. Slusky and Zeckhauser (2019) find that sunlight strongly protects against influenza, a relationship driven by sunlight in late summer, and early fall (when there are sufficient quantities of both sunlight and influenza activity).
V. iv. Government policies
Across countries, our estimates suggest that government policy, institutions, and the intensity of government response to COVID-19 are negatively associated with the mortality per capita. This evidence reflects in the coefficient estimates of stringency index, government effectiveness, democracy, health expenditures, vulnerable employees, capita GNI, and level pollution. These cross-country findings are consistent with several case studies of COVID-19. Dave et al. (2020) find in the data of U.S. states that approximately three weeks following the adoption of a Shelter-in in-Place Orders (SIPO), cumulative COVID-19 cases fell by 44 percent and, in an event-study analysis, that SIPO-induced case reductions grew larger over time, with the early adopters and high population density states appear to reap larger benefits from their SIPOs, though the estimated mortality reduction effects were imprecisely estimated. This finding is consistent with our estimates of the stringency index under the local projection approach. 
Our finding in the cross-country data on the importance of the extent of vulnerable employees is largely consistent with the evidence from influenza. Markowitz, Nesson, and Robinson (2019) find in the U.S. data that a one percentage point increase in the employment rate increases the number of influenza-related doctor visits by about 16 percent; these effects are highly pronounced in the retail sector and healthcare sector, the sectors with the highest levels of interpersonal contact. Clay, Lewis, and Sevenini (2018) find evidence on the link between air pollution and influenza infection and suggest that poor air quality was an important cause of mortality during the pandemic.
The empirical issues remain on the endogeneity of mobility and in-bound/out-bound travels to government response in the estimation. For instance, Gupta et al. (2020) find that mobility fell substantially in all the U.S. states, even ones that have not adopted major distancing mandates. They find that there is little evidence, for example, that stay-at-home mandates induced distancing; i. In contrast, early and information-focused actions have had bigger effects. Their eEvent studies show that first case announcements, emergency declarations, and school closures reduced mobility by 1-5% after 5 days and 7-45% after 20 days. We are in the process of addressing endogenous regressors in our estimation (policy stringency, lagged mortality, and mobility) with more updated data.

VI.   Exceptional country cases of interest, and future research, and closing remarks
There are countries oft-cited as exceptionally better or worse than predicted in terms of their infection and mortality rates. The contributing factors are likely to be many, including that s. Several of these countriesem previously experienced recent outbreaks, including SARS-CoV-1 (2002-2004) and Ebola (2014-2016). 
Worse: Brazil, Ecuador, Iran, Italy, Peru, United States
Better:	Cambodia, Greece, India, Indonesia, Iraq, Japan, Lebanon, Myanmar, South Korea, Sub-Saharan Africa (including Ebola-affected areas), Thailand, Venezuela, Vietnam
As the pandemic and the new data unfolds, we are in the process of analyzing these exceptional cases for country-specific factors contributing tounderlying their mortality rates from COVID-19.  
We conclude by cautioning that our results are subject to data limitations, including undercounts of COVID-19 infections and mortality.  ‘Better or worse performance’ of a country in the first phase of the pandemic does not guarantee similar future outcomes. Flattening the mortality and infection curves may shift mortality and painful adjustment forwards. Premature opening of the economy without proper testing, contact-tracing, and selective quarantines of valuable vulnerable or impacted segments of the population may induce future acceleration of the pandemic ([Acemoglu et al.,  (2020)].  More medical research and advances towards better treatment and possible vaccinations, the quality of local and global public policies, and adjustment capabilities of countries will determine future dynamics of the pandemic (Lipsitch et al.,  (2020)). 

References
Acemoglu Daron, Victor Chernozhukov, Iván Werning, and Michael D. Whinston, (2020,) “A Multi-Risk SIR Model with Optimally Targeted Lockdownm,” NBER Working Paper No. 27102
Allcott, Hunt, Levi Boxell, Jacob C. Conway, Matthew Gentzkow, Michael Thaler, David Y. Yang, 2020, Polarization and Public Health: Partisan Differences in Social Distancing during the Coronavirus Pandemic, NBER Working Paper No. 26946.
Atkeson, Andrew, 2020, How Deadly Is COVID-19? Understanding The Difficulties With Estimation Of Its Fatality Rate, NBER Working Paper No. 26965.
Avery, Christopher, William Bossert, Adam Clark, Glenn Ellison, and Sara Fisher Ellison, 2020, Policy Implications of Models of the Spread of Coronavirus: Perspectives and Opportunities for Economists, NBER Working Paper No. 27007.
Clay, Karen, Lewis, Joshua, and Severnini, Edson, 2018, Pollution, Infectious Disease, and Mortality: Evidence from the 1918 Spanish Influenza Pandemic, Journal of Economic History, 1179-1209.
“COVID-19 May Be Far More Prevalent than Previously Thought.” Theeconomist.com, The Economist, 2020, www.economist.com/graphic-detail/2020/04/01/COVID-19-may-be-far-more-prevalent-than-previously-thought.
Cox, David R., 1972,  "Regression models and life‐tables." Journal of the Royal Statistical Society: Series B (Methodological) 34, no. 2, 187-202.
Dave, Dhaval M., Andrew I. Friedson, Kyutaro Matsuzawa, Joseph J. Sabia, 2020, When Do Shelter-in-Place Orders Fight COVID-19 Best? Policy Heterogeneity Across States and Adoption Time, NBER Working Paper No. 27091.
Economist Intelligence Unit, 2019 “Data Publishing Language - Country Coordinates,”, developers.google.com, Google, 2020, 
https://developers.google.com/public-data/docs/canonical/countries_csv.
EIU, “Democracy Index.” EIU Democracy Index 2019 - World Democracy Report, , www.eiu.com/topic/democracy-index?&zid=democracyindex2019&utm_source=blog&utm_medium=blog&utm_name=democracyindex2019&utm_term=democracyindex2019&utm_content=top_link.
Freedom House, 2020, “Freedom in the World.” Freedomhouse.org, Freedom House, 2020, 
freedomhouse.org/countries/freedom-world/scores.
Grambsch, Patricia M.  and Therneau, Terry M. , 1994, Proportional hazards tests and diagnostics based on weighted residuals, Biometrika, Volume 81, Issue 3, September 1994, Pages 515–526, https://doi.org/10.1093/biomet/81.3.515
George, Brandon, Seals, Samantha, and Aban, Inmaculada, 2014, Survival analysis and regression models, Journal of Nuclear Cardiology, 21, 4, 686-694.
Gupta, Sumedha, Thuy D. Nguyen, Felipe Lozano Rojas, Shyam Raman, Byungkyu Lee, Ana Bento, Kosali I. Simon, Coady Wing, 2020, Tracking Public and Private Responses to the COVID-19 Epidemic: Evidence from State and Local Government Actions, NBER Working Paper No. 27027.
Ferguson, Neil, and Bhatt, Samir, 2020, Estimating the number of infections and the impact of nonpharmaceutical interventions on COVID-19 in 11 European countries, Imperial College London.
Fetzer, Thiemo R., Marc Witte, Lukas Hensel, Jon Jachimowicz, Johannes Haushofer, Andriy Ivchenko, Stefano Caria, Elena Reutskaja, Christopher P. Roth, Stefano Fiorin, Margarita Gómez, Gordon Kraft-Todd, Friedrich M. Götz, and Erez Yoeli, 2020, Global Behaviors and Perceptions at the Onset of the COVID-19 Pandemic, NBER Working Paper No. 27082.
Kuchler, Theresa, Dominic Russel, Johannes Stroebel, 2020, The Geographic Spread of COVID-19 Correlates with Structure of Social Networks as Measured by Facebook, NBER Working Paper No. 26990.
Lipsitch, Marc, David L. Swerdlow, and Lyn Finelli. 2020, Defining the epidemiology of COVID-19—studies needed." New England Journal of Medicine 382.13: 1194-1196.
Jordà, Òscar, 2005, "Estimation and inference of impulse responses by local projections." American economic review 95.1, 161-182.
Judson, Ruth A., and Ann L. Owen. "Estimating dynamic panel data models: a guide for macroeconomists." Economics letters 65.1 (1999): 9-15.
Hale, Thomas, Sam Webster, Anna Petherick, Toby Phillips, and Beatriz Kira (2020). Oxford COVID-19 Government Response Tracker, Blavatnik School of Government.
International Monetary Fund, 2020, “Policy Responses to COVID19.” www.imf.org/en/Topics/imf-and-COVID19/Policy-Responses-to-COVID-19.
“International Classification of Diseases (v10.0).” Who.org, World Health Organization, 2019, icd.who.int/browse10/2019/en.
Manski, Charles F., Francesca Molinari, 2020, Estimating the COVID-19 Infection Rate: Anatomy of an Inference Problem, NBER Working Paper No. 27023.
Markowitz, Sara, Nesson, Erik, and Robinson, Joshua J.,2019, The effects of employment on influenza rates, Economics & Human Biology, 34, 286-295.
“Mobility”, apple.com, Apple, 2020, https://www.apple.com/COVID19/mobility. 
“National Material Capabilities (v5.0).” Correlatesofwar.org, Correlates of War, 10 Feb. 2017, 
correlatesofwar.org/data-sets/national-material-capabilities.
Nickell, Stephen. “Biases in Dynamic Models with Fixed Effects.” Econometrica, vol. 49, no. 6, 1981, pp. 1417–1426. JSTOR, www.jstor.org/stable/1911408. Accessed 7 May, 2020.
“Novel Coronavirus COVID-19 (2019-nCoV)”, github.com, JHU CSSE, 2020, https://github.com/CSSEGISandData/COVID-19/blob/master/csse_COVID_19_data/csse_COVID_19_time_series/time_series_COVID19_confirmed_global.csv.
“Our World in Data”, ourworldindata.org, 2020, https://ourworldindata.org/coronavirus-testing.
“Policy Responses to COVID19.” Imf.org, International Monetary Fund, 2020, 
www.imf.org/en/Topics/imf-and-COVID19/Policy-Responses-to-COVID-19.
Sam, Cedric, et al. “Mapping the Coronavirus Outbreak Across the World.” Bloomberg.com, Bloomberg, 2020, www.bloomberg.com/graphics/2020-coronavirus-cases-world-map/.
Slusky, David, and Zeckhauser, Richard J., 2019, Sunlight and Protection Against Influenza, NBER Working Paper No. 24340.
Stojkoski, Viktor, Zoran Utkovski, Petar Jolakoski, Dragan Tevdovski, Ljupco Kocarev, 2020, The socio-economic determinants of the coronavirus disease (COVID-19) pandemic, arXiv:2004.07947 (physics). 
The  Economist “The South Is Likely to Have America's Highest Death Rate from COVID-19.” 2020, www.economist.com/graphic-detail/2020/04/25/the-south-is-likely-to-have-americas-highest-death-rate-from-COVID-19.
The Economist, 2020, “COVID-19 May Be Far More Prevalent than Previously Thought.” www.economist.com/graphic-detail/2020/04/01/COVID-19-may-be-far-more-prevalent-than-previously-thought.

“World Development Indicators.” Worldbank.org, World Bank, 2020, data.worldbank.org/indicator.
Viktor Stojkoski, Zoran Utkovski, Petar Jolakoski, Dragan Tevdovski, Ljupco Kocarev, The socio-economic determinants of the coronavirus disease (COVID-19) pandemic, arXiv:2004.07947 (physics). 
Verity R., LC Okell, I Dorigatti et al. (2020) Estimates of the severity of coronavirus disease 2019: a model-based analysis. Lancet Infectious Diseases, 30-03-2020; published online. https://doi.org/10.1016/S1473-3099(20)30243-7
World Health Organization, 2019, “International Classification of Diseases (v10.0),.” Who.org, World Health Organization, 2019, icd.who.int/browse10/2019/en.

World Bank, 2020, World Development Indicators, data.worldbank.org/indicator.
